name: Bump version

on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit # download the code from triggering commit
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: git config
        run: |
          git config --global user.name 'uiuytb'
          git config --global user.email 'uiuytb@users.noreply.github.com'

      - name: Bump version
        run: |
          npm version patch -m "Changement de version (%s)"

      - name: push
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/$GITHUB_REPOSITORY
          git push --follow-tags
